# Generated by Django 2.2.5 on 2023-02-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Melee', 'Melee'), ('Ranged', 'Ranged'), ('Magic', 'Magic')], default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('atk_stab', models.IntegerField(default=0)),
                ('atk_slash', models.IntegerField(default=0)),
                ('atk_crush', models.IntegerField(default=0)),
                ('atk_magic', models.IntegerField(default=0)),
                ('atk_range', models.IntegerField(default=0)),
                ('def_stab', models.IntegerField(default=0)),
                ('def_slash', models.IntegerField(default=0)),
                ('def_crush', models.IntegerField(default=0)),
                ('def_magic', models.IntegerField(default=0)),
                ('def_range', models.IntegerField(default=0)),
                ('bns_strength', models.IntegerField(default=0)),
                ('bns_range', models.IntegerField(default=0)),
                ('bns_magic', models.IntegerField(default=0)),
                ('bns_prayer', models.IntegerField(default=0)),
                ('slot', models.CharField(choices=[('N/A', 'N/A'), ('Head', 'Head'), ('Cape', 'Cape'), ('Neck', 'Neck'), ('Ammunition', 'Ammunition'), ('Weapon', 'Weapon'), ('Shield', 'Shield'), ('Body', 'Body'), ('Legs', 'Legs'), ('Hands', 'Hands'), ('Feet', 'Feet'), ('Ring', 'Ring')], default='', max_length=60)),
                ('speed', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('image', models.URLField(default='', max_length=255)),
            ],
        ),
    ]
