# Generated by Django 2.2.5 on 2023-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Melee', 'Melee'), ('Ranged', 'Ranged'), ('Magic', 'Magic')], default='', max_length=20),
        ),
    ]
